### ISSUE TITLE
Add additional licensing statements to IG landing page.

### ISSUE THREAD

**Issue by preston** [logicahealth/covid-19#4]
Submitted OBO Carol Macumber of Clinical Architecture and agreed to be Stan:

For any specification that references external terminologies, it’s HL7’s policy to include the following Copyright statement.
 
"This HL7 specification contains and references intellectual property owned by third parties ("Third Party IP").  Implementers and testers of this specification SHALL abide by the license requirements for each terminology content artifact utilized within a functioning implementation. Terminology licenses SHALL be obtained from the Third Party IP owner for each code system and/or other specified artifact used. It is the sole responsibility of each organization deploying or testing this specification to ensure their implementations comply with licensing requirements of each Third Party IP."
 
Thanks,
Carol (as vice-chair of HL7 Terminology Authority)

**Comment by nrdavis1** [comment]
Added the new language yesterday.  Waiting to see changes before I close this issue.

**Comment by preston** [comment]
Just went out with v0.3.0.
